#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use LaravelExpansions\Function\Types\Event;

/**
 * lambda handler
 * 
 * @param object $event
 */
return function ($event) {
    return (new Event($event))->dispatch();
};
